services:

  api:
    build:
      context: ./api
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./data/artifacts:/app/artifacts
      # - ./data/db.sqlite:/app/db.sqlite

    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - api/.env.dev

  front:
    build:
      context: ./frontend
    working_dir: /app
    command: sh -c "npm install && npm run build && npx serve -s build -l 3000"
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env.development
networks:
  localnetwork:
    driver: bridge
    name: localnetwork
