services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    command: make run-frontend
    restart: always
    ports:
      - "8501:8501"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    command: make run-backend
    restart: always
    ports:
      - "8080:8080"
